language: ruby
script: "bundle exec rspec spec"
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
env:
  - CI=true
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: jruby
dist: trusty
