language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
env:
  - CI=true
rvm:
  - 2.2
  - 2.3
  - 2.4
  - jruby-9
  - rbx-3
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-9
    - rvm: rbx-3
dist: trusty
